parameters:
  perlbrew_root: $(Pipeline.Workspace)/perl5/perlbrew

steps:
  - template: ../shared/install-perlbrew.yml
  - task: CacheBeta@1
    displayName: Define perl install
    inputs:
      key: '"v1" | "perl" | "5.30.1" | ./deploy/cpanfile'
      path: ${{ parameters.perlbrew_root }}/perls/perl-5.30.1
  - bash: |
      set -e
      set -x
      if [ ! -d "${{ parameters.perlbrew_root }}/perls/perl-5.30.1" ]; then
          "${{ parameters.perlbrew_root }}/bin/perlbrew" install --verbose --notest --noman -j $(nproc) 5.30.1
      fi
    displayName: Perlbrew install Perl 5.30.1
  - bash: |
      set -e
      set -x
      mkdir "$(Pipeline.Workspace)/bin" && \
      curl -fsSL --compressed https://git.io/cpm > "$(Pipeline.Workspace)/bin/cpm" && \
      chmod 0755 "$(Pipeline.Workspace)/bin/cpm"
    displayName: Install cpm
  - bash: |
      set -e
      set -x
      "${{ parameters.perlbrew_root }}/bin/perlbrew" exec --with 5.30.1 \
      "$(Pipeline.Workspace)/bin/cpm" install \
      --global \
      --show-build-log-on-failure \
      --verbose \
      --workers 16 \
      --cpanfile ./deploy/cpanfile
    displayName: Install prereqs
